CSS = r'''
:root{color-scheme:dark;--bg:#080c11;--panel:#111821;--panel2:#0c131b;--line:#293747;--muted:#95a5ba;--text:#f4f7fb;--accent:#78afff;--good:#55d58c;--warn:#f2c35d;--bad:#ff7777}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.45}.wrap{max-width:1080px;margin:auto;padding:14px}.top{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;padding-bottom:4px}.top h1{font-size:25px;line-height:1.1;margin:0}.muted,.note{color:var(--muted);font-size:12px}.hub{color:var(--accent);text-decoration:none;font-size:13px}.banner{margin:10px 0;padding:10px;border:1px solid var(--warn);border-radius:12px;color:var(--warn)}
.tabs{display:flex;gap:7px;overflow:auto;position:sticky;top:0;z-index:10;background:rgba(8,12,17,.96);padding:10px 0;scrollbar-width:none}.tabs::-webkit-scrollbar{display:none}.tabs button,.filters button,.filters select,.filters input,.smallbtn{min-height:42px;border:1px solid var(--line);background:var(--panel);color:var(--text);border-radius:999px;padding:8px 14px;white-space:nowrap;font-size:13px}.tabs button.active{border-color:var(--accent);color:var(--accent);background:rgba(120,175,255,.09)}.view{display:none}.view.active{display:block}
.hero{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:8px 0 10px}.metric,.section,.decision-strip{background:var(--panel);border:1px solid var(--line);border-radius:15px}.metric{padding:12px}.metric small{color:var(--muted);font-size:11px}.metric strong{display:block;font-size:20px;margin-top:3px}.section{padding:13px;margin-bottom:10px}.section h2{font-size:17px;margin:0}.section-head{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-bottom:10px}.section-head>span{color:var(--muted);font-size:11px;text-align:right}.summary pre{margin:0;white-space:pre-wrap;font:inherit;font-size:14px;line-height:1.6}
.decision-strip{display:grid;grid-template-columns:repeat(3,1fr);overflow:hidden;margin-bottom:10px}.decision-strip button{border:0;border-right:1px solid var(--line);background:transparent;color:var(--text);padding:12px}.decision-strip button:last-child{border-right:0}.decision-strip small{display:block;color:var(--muted)}.decision-strip strong{font-size:22px}
.candidate-list{display:grid;gap:8px}.candidate{background:var(--panel2);border:1px solid var(--line);border-radius:12px;overflow:hidden}.candidate.actionable{border-color:rgba(85,213,140,.55)}.candidate.avoid{border-color:rgba(255,119,119,.32)}.candidate summary{list-style:none;cursor:pointer;padding:11px}.candidate summary::-webkit-details-marker{display:none}.candidate-title,.candidate-sub{display:flex;justify-content:space-between;gap:8px;align-items:center}.ticker{font-size:18px;color:var(--accent)}.rank{font-size:10px;color:var(--muted);margin-left:5px}.candidate-sub{font-size:11px;color:var(--muted);margin:4px 0 9px;flex-wrap:wrap}.badge,.phase{font-size:10px;font-weight:800;padding:3px 7px;border-radius:99px}.badge.actionable,.phase.good{background:rgba(85,213,140,.14);color:var(--good)}.badge.ready,.phase.neutral{background:rgba(120,175,255,.13);color:var(--accent)}.badge.avoid,.phase.bad{background:rgba(255,119,119,.14);color:var(--bad)}
.decision-grid{display:grid;grid-template-columns:1.5fr 1.35fr .65fr;gap:6px}.value-tile{background:#091019;border-radius:9px;padding:7px 8px;min-width:0}.value-tile small{display:block;color:var(--muted);font-size:9px}.value-tile strong{display:block;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.value-tile.risk strong{color:var(--warn)}.reason-head{margin:8px 0 0;color:#c7d2df;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.candidate-detail{border-top:1px solid var(--line);padding:10px}
.kv{display:grid;grid-template-columns:minmax(88px,.8fr) minmax(0,1.2fr);gap:5px 8px;font-size:12px}.kv.compact{font-size:11px}.kv span{color:var(--muted)}.kv b{text-align:right;overflow-wrap:anywhere}.reasons{margin:9px 0 0;padding-left:18px;font-size:11px;color:var(--muted)}.reasons li{margin:3px 0}.text-button{border:0;background:transparent;color:var(--accent);padding:10px 0 0;font-weight:700}.filters{display:flex;gap:7px;margin:8px 0 10px;overflow:auto}.filters input{border-radius:10px;min-width:170px}
.empty-state{padding:18px;background:var(--panel2);border:1px dashed var(--line);border-radius:11px;color:var(--muted)}.empty-state b,.empty-state span{display:block}.empty-state b{color:var(--text);margin-bottom:3px}.split-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.item{background:var(--panel2);border:1px solid var(--line);border-radius:11px;padding:10px}.item h3{font-size:14px;color:var(--accent);margin:0 0 8px}
.signal-list{display:grid;gap:5px}.signal-row{display:grid;grid-template-columns:1fr 140px;gap:12px;align-items:center;background:var(--panel2);border-radius:10px;padding:9px}.signal-row b,.signal-row small{display:block}.signal-row small{color:var(--muted);font-size:10px}.signal-value{text-align:right}.signal-value strong{font-size:12px}.signal-value span{display:block;height:4px;background:#1b2633;border-radius:99px;overflow:hidden;margin-top:4px}.signal-value i{display:block;height:100%;background:var(--accent)}
.table-wrap{overflow:auto;border:1px solid var(--line);border-radius:11px}table{border-collapse:collapse;width:100%;min-width:520px;font-size:12px}th,td{padding:9px 10px;text-align:right;border-bottom:1px solid rgba(41,55,71,.7)}th:first-child,td:first-child{text-align:left}th{position:sticky;top:0;background:#111a24;color:var(--muted);font-size:10px}tbody tr:last-child td{border-bottom:0}.subline{display:block;color:var(--muted);font-size:9px;font-weight:400;margin-top:2px}.more{margin-top:9px}.more>summary{cursor:pointer;color:var(--accent);font-size:12px;padding:7px 0}.leader-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}
.info-panel{display:flex;gap:10px;align-items:flex-start}.info-panel b{white-space:nowrap}.info-panel span{color:var(--muted);font-size:12px}.copy{width:100%;min-height:120px;max-height:65vh;resize:vertical;background:#080c11;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:12px;font:inherit;font-size:13px;line-height:1.5}.copybtn{margin-top:8px;border:0;border-radius:9px;padding:10px 16px;background:var(--accent);color:#08111e;font-weight:800}.smallbtn{min-height:34px;padding:5px 10px}
@media(max-width:800px){.leader-grid{grid-template-columns:1fr}.split-grid{grid-template-columns:1fr}.hero{grid-template-columns:1fr 1fr}}
@media(max-width:580px){.wrap{padding:10px}.top{align-items:flex-start;flex-direction:column}.top h1{font-size:22px}.metric{padding:10px}.metric strong{font-size:18px}.section{padding:10px}.tabs{margin:0 -10px;padding:9px 10px}.tabs button{min-height:40px;padding:7px 12px}.decision-grid{grid-template-columns:1.45fr 1.25fr .65fr}.value-tile{padding:6px}.value-tile strong{font-size:11px}.signal-row{grid-template-columns:1fr 110px}.filters{margin-right:-10px}.candidate summary{padding:10px}.summary pre{font-size:13px}.table-wrap{margin:0 -1px}}
@media print{.tabs,.filters,.copybtn,.smallbtn,.text-button{display:none}.view{display:block!important}.section{break-inside:avoid}}
'''

SCRIPT = r'''
function activateTab(id){document.querySelectorAll('[data-tab]').forEach(item=>item.classList.toggle('active',item.dataset.tab===id));document.querySelectorAll('.view').forEach(item=>item.classList.toggle('active',item.id===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>activateTab(button.dataset.tab));
function applyFilters(){const status=document.getElementById('statusFilter')?.value||'ALL';const setup=document.getElementById('setupFilter')?.value||'ALL';const query=(document.getElementById('tickerSearch')?.value||'').toUpperCase();document.querySelectorAll('#candidateList .candidate').forEach(card=>{const okStatus=status==='ALL'||card.dataset.status===status;const okSetup=setup==='ALL'||card.dataset.setup===setup;const okQuery=!query||card.textContent.toUpperCase().includes(query);card.style.display=okStatus&&okSetup&&okQuery?'':'none'})}
document.getElementById('statusFilter')?.addEventListener('change',applyFilters);document.getElementById('setupFilter')?.addEventListener('change',applyFilters);document.getElementById('tickerSearch')?.addEventListener('input',applyFilters);
function resetFilters(){document.getElementById('statusFilter').value='ALL';document.getElementById('setupFilter').value='ALL';document.getElementById('tickerSearch').value='';applyFilters()}
function openCandidates(status){activateTab('candidates');document.getElementById('statusFilter').value=status;applyFilters()}
function copyArea(id){const node=document.getElementById(id);navigator.clipboard.writeText(node.value)}function copyText(text){if(text&&text!=='—')navigator.clipboard.writeText(text)}
document.querySelectorAll('textarea.copy').forEach(node=>{node.style.height='auto';node.style.height=Math.min(node.scrollHeight+4,window.innerHeight*.65)+'px'})
'''
