#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Repair the one known legacy f-string and compile under the workflow's Python 3.11.

The source was once generated by Python 3.12+ where PEP 701 allows backslashes
inside f-string expressions. GitHub Actions intentionally runs Python 3.11, so
we normalize that fragment before py_compile. Already-fixed source is a no-op.
"""
from pathlib import Path
import hashlib
import sys

PATH = Path("build_dashboard.py")
source = PATH.read_text(encoding="utf-8")

old = '''            rows.append(
                f'<tr><td><b data-tkone="{t}">{t}</b>{"<span class=\\"chip\\" style=\\"margin-left:5px\\">"+stat+"</span>" if stat else ""}</td>'
                f'<td>{th} <span class="{_qcls.get(quad, "mut")}" style="font-size:10px">{quad}</span></td>'
                f'<td>{r1:.0f} / {r2:.0f}</td><td>{d52t}</td></tr>')'''

new = '''            stat_chip = (
                f'<span class="chip" style="margin-left:5px">{stat}</span>'
                if stat else ""
            )
            quad_cls = _qcls.get(quad, "mut")
            rows.append(
                f'<tr><td><b data-tkone="{t}">{t}</b>{stat_chip}</td>'
                f'<td>{th} <span class="{quad_cls}" style="font-size:10px">{quad}</span></td>'
                f'<td>{r1:.0f} / {r2:.0f}</td><td>{d52t}</td></tr>'
            )'''

count = source.count(old)
if count > 1:
    raise SystemExit("[preflight] unexpected duplicate legacy fragment: %d" % count)
if count == 1:
    source = source.replace(old, new, 1)
    PATH.write_text(source, encoding="utf-8")
    print("[preflight] repaired legacy Python 3.11-incompatible f-string")
else:
    print("[preflight] legacy fragment absent; source already repaired")

# This is executed by Python 3.11 in Actions, so it is the authoritative parser check.
compile(source, str(PATH), "exec")
sha = hashlib.sha256(source.encode("utf-8")).hexdigest()
print("[preflight] Python %s compile OK | sha256=%s" % (sys.version.split()[0], sha))
