from __future__ import annotations

import argparse
from pathlib import Path

from .almanac import CSS


LIVE_CSS = r"""
.tabs{grid-template-columns:repeat(12,minmax(0,1fr))}
.tab:nth-child(-n+4){grid-column:span 3}.tab:nth-child(n+5){grid-column:span 4}
html.js .tab-panel{display:none}html.js .tab-panel.active{display:block}
html:not(.js) .tab-panel{display:none}html:not(.js) .tab-panel.active{display:block}
html:not(.js) .tab-panel:target{display:block}
html:not(.js):has(.tab-panel:target) .tab-panel.active:not(:target){display:none}
.sync-banner{margin:12px 14px 0;padding:10px 11px;border:1px solid var(--line-strong);border-radius:var(--radius);background:var(--panel);font-size:9px;line-height:1.55}
.sync-banner strong{display:block;font-size:11px}.sync-banner.good{background:var(--good-soft);border-color:#b7d7c3}.sync-banner.warn{background:var(--warn-soft);border-color:#dbc69d}.sync-banner.bad{background:var(--bad-soft);border-color:#e4bcb1}
.sync-actions{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.sync-actions a,.sync-actions button{min-height:30px;padding:5px 9px;border:1px solid var(--line-strong);border-radius:7px;background:var(--panel);color:var(--text);font:800 9px -apple-system,sans-serif;text-decoration:none;cursor:pointer}
.pair-row{display:grid;grid-template-columns:94px minmax(0,1fr) 44px;gap:7px;align-items:center;padding:6px 0;font-size:9px}.pair-row+.pair-row{border-top:1px solid var(--line)}.pair-track{height:6px;background:var(--bg-alt);border-radius:99px;overflow:hidden}.pair-track i{display:block;height:100%;background:var(--accent);border-radius:99px}.pair-row strong{text-align:right}
.dd-row{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(0,.8fr) auto;gap:7px;align-items:center;padding:7px 0}.dd-row+.dd-row{border-top:1px solid var(--line)}.dd-row b{font-size:10px}.dd-row small,.dd-row span{display:block;color:var(--muted);font-size:7px}.dd-row em{font-style:normal;font-size:7px;font-weight:800;color:var(--bad)}
.source-note{margin-top:8px;padding:8px;border:1px dashed var(--line-strong);border-radius:8px;color:var(--muted);font-size:8px;line-height:1.55}
.empty-action{display:grid;gap:8px;padding:18px 12px;text-align:center;color:var(--muted);font-size:10px;border:1px dashed var(--line-strong);border-radius:var(--radius)}.empty-action b{color:var(--text);font-size:12px}.empty-action a{justify-self:center;color:var(--accent);font-weight:800}
"""


def render_live_dashboard(path: Path) -> None:
    document = f'''<!doctype html><html lang="ja"><head><script>document.documentElement.classList.add("js")</script><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="same-origin"><title>Swinote</title><style>{CSS}{LIVE_CSS}</style></head><body><main class="app"><header class="topbar"><div class="brand"><div class="mark"><small>SWINOTE</small>Trade Journal</div><div class="asof"><span id="asof">—</span><br><span id="freshness">同期中</span></div></div><div class="acct-line"><span>登録保有評価額<strong class="num" id="registered-value">—</strong></span><span>総資産<strong class="num" id="account-equity">—</strong></span><span>登録Gross<strong class="num" id="gross-exposure">—</strong></span></div></header>
<div class="sync-banner warn" id="sync-banner"><strong id="sync-title">データを同期中</strong><span id="sync-detail">最新データを確認しています。</span><div class="sync-actions"><button id="sync-now" type="button">再同期</button></div></div>
<nav class="tabs" role="tablist" aria-label="Swinote navigation"><a class="tab" href="#today" data-tab="today" role="tab" aria-controls="today" aria-selected="true">今日</a><a class="tab" href="#assets" data-tab="assets" role="tab" aria-controls="assets" aria-selected="false">資産</a><a class="tab" href="#portfolio" data-tab="portfolio" role="tab" aria-controls="portfolio" aria-selected="false">保有</a><a class="tab" href="#journal" data-tab="journal" role="tab" aria-controls="journal" aria-selected="false">履歴</a><a class="tab" href="#edge" data-tab="edge" role="tab" aria-controls="edge" aria-selected="false">エッジ</a><a class="tab" href="#review" data-tab="review" role="tab" aria-controls="review" aria-selected="false">振り返り</a><a class="tab" href="#share" data-tab="share" role="tab" aria-controls="share" aria-selected="false">共有</a></nav><noscript><div class="noscript">このページの表示にはJavaScriptが必要です。</div></noscript><div class="panel-wrap">
<section class="tab-panel active" id="today"><div class="sec-head"><h2>今日の運用</h2><p>最新の資産・保有状況</p><div class="rule"></div></div><div class="status-line warn" id="decision"><span class="status-dot"></span><span><b id="decision-title">同期中</b><small id="decision-reason">データ取得完了まで発注判断を表示しません</small></span><a class="detail-link" href="#portfolio">内訳 →</a></div><div class="metrics"><div class="metric"><span>本日</span><strong class="num" id="daily-return">—</strong><small>口座評価額</small></div><div class="metric"><span>月初来</span><strong class="num" id="mtd-return">—</strong><small>MTD</small></div><div class="metric"><span>年初来</span><strong class="num" id="ytd-return">—</strong><small>YTD</small></div><div class="metric"><span>最大DD</span><strong class="num neg" id="max-dd">—</strong><small>取得期間</small></div></div><div class="panel"><h3>今日見る保有</h3><div class="sub">撤退線までの距離が近い順</div><div id="watch-list"><div class="stub">同期中</div></div></div><div class="metrics"><div class="metric"><span>名目Heat</span><strong class="num" id="nominal-heat">—</strong></div><div class="metric"><span>Stop逸脱</span><strong class="num" id="stop-breached">—</strong></div><div class="metric"><span>Stop接近</span><strong class="num" id="stop-near">—</strong></div><div class="metric"><span>保有数</span><strong class="num" id="holding-count">—</strong></div></div><p class="fineprint">候補銘柄は約定扱いにせず、実際の保有・決済記録だけを集計します。</p></section>
<section class="tab-panel" id="assets"><div class="sec-head"><h2>資産推移</h2><p>口座評価額の推移</p><div class="rule"></div></div><div class="period-bar" id="assets-period"><button class="period-btn" data-period="1m">1ヶ月</button><button class="period-btn" data-period="3m">3ヶ月</button><button class="period-btn" data-period="ytd" aria-pressed="true">YTD</button><button class="period-btn" data-period="all">全期間</button></div><div class="metrics"><div class="metric"><span>リターン</span><strong class="num" id="a-ret">—</strong></div><div class="metric"><span>PF</span><strong class="num" id="a-pf">—</strong></div><div class="metric"><span>勝率</span><strong class="num" id="a-wr">—</strong></div><div class="metric"><span>平均R</span><strong class="num" id="a-r">—</strong></div><div class="metric"><span>最大DD</span><strong class="num neg" id="a-dd">—</strong></div><div class="metric"><span>取引数</span><strong class="num" id="a-n">—</strong></div></div><div class="panel"><h3>Equity Curve</h3><div class="sub">口座評価額の履歴</div><svg class="equity-svg" viewBox="0 0 600 190" id="equity-svg"></svg><div class="stub" id="equity-empty">資産履歴なし</div></div><div class="panel"><h3>月次リターン</h3><div class="month-grid" id="month-grid"></div></div><div class="panel"><h3>Drawdown Episodes</h3><div id="dd-list"></div></div></section>
<section class="tab-panel" id="portfolio"><div class="sec-head"><h2>ポートフォリオ</h2><p><span id="portfolio-count">—</span>｜保有銘柄</p><div class="rule"></div></div><div class="metrics"><div class="metric"><span>名目Heat</span><strong class="num" id="p-heat">—</strong></div><div class="metric"><span>登録Gross</span><strong class="num" id="p-gross">—</strong></div><div class="metric"><span>ポートフォリオADR%</span><strong class="num" id="p-adr">—</strong><small id="p-adr-coverage">カバー率 —</small></div><div class="metric"><span>最大テーマ</span><strong id="p-cluster">—</strong></div></div>
<details class="panel sizer" id="sizing-calculator"><summary><span><h3>自由サイジング</h3><span class="sub">2分割Entry × 21EMA Low / 10MA × +25%で25%利確</span></span></summary><div class="sizer-body"><div class="sizer-grid"><label><span>口座総資産（円）</span><input id="sz-equity" type="number" inputmode="decimal" min="0" placeholder="総資産"></label><label><span>1トレードリスク%</span><input id="sz-risk" type="number" inputmode="decimal" min="0.01" step="0.1" value="0.6"></label><label><span>建率上限%</span><input id="sz-cap" type="number" inputmode="decimal" min="0.1" step="0.5" value="8"></label><label><span>FX→円（日本株は1）</span><input id="sz-fx" type="number" inputmode="decimal" min="0.0001" step="0.01"></label><label><span>1st Entry</span><input id="sz-entry1" type="number" inputmode="decimal" min="0" step="0.01"></label><label><span>2nd Entry</span><input id="sz-entry2" type="number" inputmode="decimal" min="0" step="0.01" placeholder="未定なら1stと同値"></label><label><span>1stの配分%</span><input id="sz-split1" type="number" inputmode="decimal" min="1" max="99" step="1" value="50"></label><label><span>撤退方法</span><select id="sz-stop-method"><option value="21EMA_LOW">21EMA Low</option><option value="10MA">10MA</option></select></label><label><span>21EMA Low</span><input id="sz-stop21" type="number" inputmode="decimal" min="0" step="0.01"></label><label><span>10MA</span><input id="sz-stop10" type="number" inputmode="decimal" min="0" step="0.01"></label></div><div class="sizer-output"><div><span>平均Entry</span><b class="num" id="sz-avg">—</b></div><div><span>総数量</span><b class="num" id="sz-qty">—</b></div><div><span>1st / 2nd</span><b class="num" id="sz-tranches">—</b></div><div><span>建率</span><b class="num" id="sz-value">—</b></div><div><span>Stop時損失</span><b class="num" id="sz-loss">—</b></div><div><span>+25%部分利確</span><b class="num" id="sz-partial">—</b></div><div><span>残す数量</span><b class="num" id="sz-runner">—</b></div><div><span>残玉トレール</span><b id="sz-trail">—</b></div></div><p class="sizer-message bad" id="sz-message">実データ同期後、必要数値を入力してください。</p></div></details>
<div class="panel"><h3>集中度</h3><div id="conc-list"></div></div><div class="panel"><h3>セクター配分</h3><div id="sector-bars"></div></div><div class="panel"><h3>テーマ配分</h3><div id="theme-bars"></div></div><div class="panel"><div class="portfolio-tools"><div><h3>保有一覧</h3><div class="sub">必要な銘柄だけ詳細を展開</div></div><button class="compact-btn" id="copy-holdings" type="button">全銘柄をコピー</button></div><div id="holdings-cards"><div class="stub">同期中</div></div></div></section>
<section class="tab-panel" id="journal"><div class="sec-head"><h2>取引履歴</h2><p>決済済みの取引</p><div class="rule"></div></div><div class="j-toolbar"><input class="search" id="j-search" type="search" placeholder="Ticker / Sector / Theme / Exit"><select id="j-setup"><option value="">Setup すべて</option></select><select id="j-nq"><option value="">NQ すべて</option><option>GREEN</option><option>BLUE</option><option>YELLOW</option><option>RED</option></select><select id="j-result"><option value="">結果 すべて</option><option value="win">勝ち</option><option value="loss">負け</option></select></div><div class="j-count" id="j-count"></div><div id="j-list"><div class="stub">同期中</div></div><button class="more-btn" id="j-more" hidden>さらに20件表示</button><p class="fineprint">損益は保存されている通貨で表示します。R倍数は初期リスク記録がある取引だけ表示します。</p></section>
<section class="tab-panel" id="edge"><div class="sec-head"><h2>エッジ分析</h2><p>実決済履歴だけを条件別集計</p><div class="rule"></div></div><div class="callout" id="edge-callout"><b>同期中</b></div><div class="edge-controls"><label><span>軸</span><select id="edge-axis"><option value="setup">Setup別</option><option value="nq">NQ環境別</option><option value="sector">Sector別</option><option value="theme">Theme別</option><option value="holdBucket">保有日数帯</option><option value="setupNq">Setup × NQ</option></select></label><label><span>並び替え</span><select id="edge-sort"><option value="pf">PF</option><option value="wr">勝率</option><option value="r">平均R</option><option value="n">件数</option></select></label><label><span>最小件数</span><input type="number" id="edge-minn" value="5" min="1" max="100"></label></div><div class="panel"><div class="rank-head"><span>条件</span><span>件数</span><span>勝率</span><span>PF</span><span>平均R</span></div><div id="rank-body"></div></div><p class="fineprint">PF・勝率は米ドル損益で計算。サンプル不足は薄色表示します。</p></section>
<section class="tab-panel" id="review"><div class="sec-head"><h2>振り返り</h2><p>記録から再現可能な事実だけを表示</p><div class="rule"></div></div><div class="panel review" id="review-body"><div class="stub">同期中</div></div></section>
<section class="tab-panel" id="share"><div class="sec-head"><h2>共有</h2><p>実績集計だけをコピー</p><div class="rule"></div></div><div class="share-preview"><div class="eyebrow" id="share-eyebrow">Swinote</div><div class="headline">期待値を残し、損失を管理する。</div><div class="share-stats"><div><span>勝率</span><strong id="share-wr">—</strong></div><div><span>Profit Factor</span><strong id="share-pf">—</strong></div><div><span>平均R</span><strong id="share-r">—</strong></div><div><span>最大DD</span><strong id="share-dd">—</strong></div></div></div><div class="panel"><h3>投稿文</h3><textarea class="copy-box" id="share-text" readonly>同期中</textarea><button class="copy-btn" id="copy-share" type="button">コピー</button></div><p class="fineprint">個別銘柄・保有金額・建値は共有文へ含めません。</p></section>
</div></main><script src="live.js"></script></body></html>'''
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(document, encoding="utf-8")


def render_legacy_redirect(path: Path) -> None:
    document = '''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="refresh" content="0;url=../swinote/"><title>移動中</title></head><body><script>location.replace("../swinote/" + location.hash)</script></body></html>'''
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(document, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Render the browser-synchronized Swinote shell")
    parser.add_argument("--output", type=Path, default=Path("swinote/index.html"))
    args = parser.parse_args()
    render_live_dashboard(args.output)
    if args.output == Path("swinote/index.html"):
        render_legacy_redirect(Path("kaview/index.html"))


if __name__ == "__main__":
    main()


__all__ = ["render_legacy_redirect", "render_live_dashboard"]
