const DATA_URL='https://raw.githubusercontent.com/thanzo12wizu-stack/v38-watchlist/research/rotation-exact-flow-internals-20260831/leadership/research/rotation_daily_observation_brief/daily_observation_brief.json';
const CONTEXT_URL='https://raw.githubusercontent.com/thanzo12wizu-stack/v38-watchlist/research/rotation-exact-flow-internals-20260831/leadership/research/rotation_theme_stock_context/rotation_theme_stock_context.json';
const ETF={XLC:'通信サービス',XLY:'一般消費財',XLP:'生活必需品',XLE:'エネルギー',XLF:'金融',XLV:'ヘルスケア',XLI:'資本財・工業',XLB:'素材',XLRE:'不動産',XLK:'テクノロジー',XLU:'公益',XBI:'バイオテック',XME:'金属・鉱業',SOXX:'半導体',IGV:'ソフトウェア'};
const STATE={
CURRENT_STRENGTH:{label:'現在強い',tone:'good',color:'#77d49e',meaning:'価格と内部が同時に強い現在状態。将来Alphaは未確認。'},
INTERNAL_LEAD_WATCH:{label:'内部先行・観測',tone:'watch',color:'#82b7da',meaning:'内部参加が価格より先行。予測シグナルではない。'},
EARLY_ROTATION_WATCH:{label:'内部改善・観測',tone:'watch',color:'#e4b967',meaning:'内部改善と流入が価格に先行。過去検証では買いシグナル不採用。'},
FLOW_INTERNAL_DIVERGENCE_WATCH:{label:'流入先行・内部未追随',tone:'watch',color:'#e4b967',meaning:'ETF流入に構成銘柄の広がりが追いついていない。'},
INTERNAL_WEAK_FLOW_OUT:{label:'内部弱＋資金流出',tone:'bad',color:'#df8a78',meaning:'内部が弱く資金も流出。分配とは別の診断状態。'},
DISTRIBUTION_WARNING:{label:'分配警戒',tone:'warn',color:'#e79a62',meaning:'価格高位・内部弱・流出。最近のPIT検証で警戒Contextとして残った。'},
DISTRIBUTION_DETERIORATION_WARNING:{label:'分配劣化警戒',tone:'warn',color:'#e79a62',meaning:'価格高位のまま内部が急低下し流出。最近の検証で警戒Contextとして残った。'},
REDEMPTION_DIVERGENCE:{label:'流出中だが内部強',tone:'watch',color:'#b5a1d8',meaning:'資金流出でも内部は強い。売り抜けとは断定しない。'},
WEAK_BREAKDOWN:{label:'弱い',tone:'bad',color:'#df7b7b',meaning:'価格と内部がともに弱い。'},
MIXED_HOLD:{label:'方向不一致',tone:'',color:'#83909e',meaning:'価格・内部・Flowの方向が揃っていない。'},
DATA_REQUIRED:{label:'データ不足',tone:'',color:'#657281',meaning:'必要データ不足。'}
};
const MODE={ATTACK:'攻撃',SELECTIVE:'選別',STOP:'新規停止',DEFENSE:'防御'};const RATING={neutral:'中立',fear:'恐怖','extreme fear':'極端な恐怖',greed:'強欲','extreme greed':'極端な強欲'};const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const isNum=v=>v!==null&&v!==''&&Number.isFinite(Number(v));const fmt=v=>isNum(v)?Number(v).toFixed(1):'—';
function stateInfo(s){return STATE[s]||{label:'未定義',tone:'',color:'#657281',meaning:'上流状態を確認'}}function etfName(t){return ETF[t]||''}function etfLabel(t){return `${t}${etfName(t)?`｜${etfName(t)}`:''}`}function modeLabel(m){return MODE[String(m||'').toUpperCase()]||m||'—'}function rating(x){return RATING[String(x||'').toLowerCase()]||x||'—'}function shortDate(s){const p=String(s||'').split('-');return p.length===3?`${p[0]}.${p[1]}.${p[2]}`:(s||'—')}
function money(v){if(!isNum(v))return'—';const n=Number(v),sg=n>=0?'+':'−',a=Math.abs(n);if(a>=1e9)return`${sg}${(a/1e9).toFixed(2)}B`;if(a>=1e6)return`${sg}${Math.round(a/1e6)}M`;return`${sg}${Math.round(a)}`}
function pct(v){if(!isNum(v))return'—';const n=Number(v);return`${n>=0?'+':''}${n.toFixed(2)}%`}
function allRows(d){return Object.values(d.observations?.rotation_buckets||{}).flat().filter(x=>x&&x.ticker)}
function sortRows(rows){const priority={CURRENT_STRENGTH:0,INTERNAL_LEAD_WATCH:1,EARLY_ROTATION_WATCH:2,REDEMPTION_DIVERGENCE:3,MIXED_HOLD:4,FLOW_INTERNAL_DIVERGENCE_WATCH:5,INTERNAL_WEAK_FLOW_OUT:6,DISTRIBUTION_WARNING:7,DISTRIBUTION_DETERIORATION_WARNING:7,WEAK_BREAKDOWN:8,DATA_REQUIRED:9};return [...rows].sort((a,b)=>(priority[a.state]??9)-(priority[b.state]??9)||Number(b.price_score||0)-Number(a.price_score||0))}
function summaryLine(r){const st=stateInfo(r.state);return `<div class="summary-line"><b class="${st.tone}">${esc(etfLabel(r.ticker))}</b> <span class="micro">${esc(st.label)}</span>${isNum(r.flow_20d_pct_aum)?` <span class="${Number(r.flow_20d_pct_aum)>=0?'good':'bad'}">${pct(r.flow_20d_pct_aum)}</span>`:''}</div>`}
function renderHero(d){const rows=allRows(d),m=d.market_when||{},mode=String(m.mode||'').toUpperCase();let action='市場モード確認待ち';if(mode==='STOP')action='通常個別株の新規エントリーは停止';if(mode==='DEFENSE')action='防御モード：通常個別株の新規停止';if(mode==='SELECTIVE')action='選別モード：新規候補を絞る';if(mode==='ATTACK')action='攻撃モード：正式V38候補を実行対象へ';$('heroAction').textContent=action;$('permission').textContent=m.new_entry_limit??'—';$('permissionSub').textContent=`NQSAR ${m.nqsar||'—'} / Breadth ${isNum(m.breadth50)?Number(m.breadth50).toFixed(1)+'%':'—'}`;
 const strong=sortRows(rows.filter(r=>r.state==='CURRENT_STRENGTH'));const watch=sortRows(rows.filter(r=>['INTERNAL_LEAD_WATCH','EARLY_ROTATION_WATCH','FLOW_INTERNAL_DIVERGENCE_WATCH','REDEMPTION_DIVERGENCE'].includes(r.state)));const risk=sortRows(rows.filter(r=>['DISTRIBUTION_WARNING','DISTRIBUTION_DETERIORATION_WARNING','INTERNAL_WEAK_FLOW_OUT','WEAK_BREAKDOWN'].includes(r.state)));
 $('summaryStrong').innerHTML=strong.slice(0,4).map(summaryLine).join('')||'<div class="summary-line">明確な強さ確認なし</div>';$('summaryWatch').innerHTML=watch.slice(0,4).map(summaryLine).join('')||'<div class="summary-line">主要な観測状態なし</div>';$('summaryRisk').innerHTML=risk.slice(0,5).map(summaryLine).join('')||'<div class="summary-line">主要警戒なし</div>';
 const sStrong=strong.filter(r=>r.level==='SECTOR').map(r=>etfLabel(r.ticker));const iStrong=strong.filter(r=>r.level==='INDUSTRY').map(r=>etfLabel(r.ticker));const dist=risk.filter(r=>String(r.state).includes('DISTRIBUTION')).map(r=>etfLabel(r.ticker));const weakInd=risk.filter(r=>r.level==='INDUSTRY').map(r=>etfLabel(r.ticker));let parts=[];if(sStrong.length)parts.push(`セクターでは ${sStrong.join(' / ')} の現在の強さを確認`);if(iStrong.length)parts.push(`業種では ${iStrong.join(' / ')} が強い`);if(dist.length)parts.push(`${dist.join(' / ')} は分配警戒`);if(weakInd.length)parts.push(`${weakInd.join(' / ')} は弱化側`);$('heroSentence').textContent=parts.length?parts.join('。')+'。':'明確な方向性は限定的です。';}
function renderMarketList(id,rows){const header=`<div class="market-row colhead"><div>ETF</div><div>状態</div><div class="num internal-col">内部</div><div class="num price-col">価格</div><div class="num">20日Flow/AUM</div></div>`;$(id).innerHTML=header+sortRows(rows).map(r=>{const st=stateInfo(r.state);return `<div class="market-row"><div class="etf-main"><span class="ticker">${esc(r.ticker)}</span><span class="etf-name">${esc(etfName(r.ticker))}</span></div><div class="state-text ${st.tone}">${esc(st.label)}</div><div class="num internal-col">${fmt(r.internal_score)}<small>内部</small></div><div class="num price-col">${fmt(r.price_score)}<small>価格</small></div><div class="num"><span class="flowpct ${Number(r.flow_20d_pct_aum)>=0?'good':'bad'}">${pct(r.flow_20d_pct_aum)}</span><small>${money(r.flow_20d_usd)}</small></div></div>`}).join('')}
function groupBy(arr,key){return arr.reduce((m,x)=>{const k=x[key]||'その他';(m[k]||(m[k]=[])).push(x);return m},{})}
function renderLeaders(d,ctx){const rows=allRows(d),stateBy={};rows.forEach(r=>stateBy[r.ticker]=r.state);const formal={};(d.theme_stock?.formal_v38_context||[]).forEach(g=>(g.stocks||[]).forEach(s=>formal[`${g.etf}:${s.symbol}`]=s));const items=ctx?.industry_context||[];const allowed=new Set(['CURRENT_STRENGTH','INTERNAL_LEAD_WATCH','EARLY_ROTATION_WATCH','REDEMPTION_DIVERGENCE']);const lp={CURRENT_STRENGTH:0,INTERNAL_LEAD_WATCH:1,EARLY_ROTATION_WATCH:2,REDEMPTION_DIVERGENCE:3};const cards=items.filter(x=>allowed.has(stateBy[x.etf])).map(item=>{const leaders=item.existing_emerging_or_leading_leaders_in_full_intersection||item.existing_emerging_or_leading_leaders_in_top15_intersection||[];return {...item,_leaders:leaders}}).filter(x=>x._leaders.length).sort((a,b)=>(lp[stateBy[a.etf]]??9)-(lp[stateBy[b.etf]]??9)||Number(b.rotation?.matrix_price_score||0)-Number(a.rotation?.matrix_price_score||0));
 $('leaderScope').textContent=ctx?.context_scope==='FULL_ETF_MEMBERSHIP_X_FULL_LEADERSHIP_EXPORT'?'ETF全構成銘柄を照合':'照合範囲に上限あり';
 $('leaders').innerHTML=cards.length?cards.map(item=>{const st=stateInfo(stateBy[item.etf]),groups=groupBy(item._leaders.slice(0,12),'group');const coverage=isNum(item.leadership_full_intersection_pct)?`${Number(item.leadership_full_intersection_pct).toFixed(0)}%`:'—';return `<div class="leader-card"><div class="leader-head"><div class="leader-title">${esc(etfLabel(item.etf))}<small>${esc(st.meaning)}</small></div><div class="leader-state ${st.tone}">${esc(st.label)}</div></div><div class="leader-coverage">構成 ${item.membership_rows??'—'}銘柄 / Leadership照合 ${item.leadership_full_intersections??item.leadership_group_top15_intersections??'—'}（${coverage}）</div>${Object.entries(groups).slice(0,3).map(([g,ls])=>`<div class="theme-block"><div class="theme-name">${esc(g)} ・ ${esc(ls[0]?.group_phase==='EMERGING'?'新興':ls[0]?.group_phase==='LEADING'?'主導':ls[0]?.group_phase||'')}</div><div class="stocks-line">${ls.slice(0,6).map(x=>{const f=formal[`${item.etf}:${x.symbol}`];return `<div class="stock-pill"><b>${esc(x.symbol)}</b><span>RS189 ${isNum(x.rs189)?Number(x.rs189).toFixed(0):'—'} / RS63 ${isNum(x.rs63)?Number(x.rs63).toFixed(0):'—'}${f&&f.attack_rank?` / V38 #${f.attack_rank}`:''}</span></div>`}).join('')}</div></div>`).join('')}</div>`}).join(''):'<div class="sub">強さ・観測状態と一致する主導銘柄はありません。</div>'}
function renderChanges(d){const ev=d.observations?.state_transitions||[];$('changes').innerHTML=ev.length?ev.slice(0,8).map(e=>`<div class="change-row"><div class="change-date">${esc(shortDate(e.date))}</div><div class="change-main"><b>${esc(etfLabel(e.ticker))}</b>：${esc(stateInfo(e.from).label)} → <span class="${stateInfo(e.to).tone}">${esc(stateInfo(e.to).label)}</span></div><div class="change-tag">状態変化</div></div>`).join(''):'<div class="sub">履歴はまだ蓄積初期です。状態が変化した日から、ここに「いつ・何から何へ変わったか」を表示します。</div>'}
function renderMatrix(id,rows){const svg=$(id),W=720,H=400,L=50,R=20,T=22,B=46,x=v=>L+(W-L-R)*Number(v)/100,y=v=>H-B-(H-T-B)*Number(v)/100;let s=`<rect x="${L}" y="${T}" width="${W-L-R}" height="${H-T-B}" fill="#0b1117"/>`;[0,25,50,75,100].forEach(v=>{const c=v===50?'#34404d':'#202833',dash=v===50?'5 5':'0';s+=`<line x1="${x(v)}" y1="${T}" x2="${x(v)}" y2="${H-B}" stroke="${c}" stroke-dasharray="${dash}"/><line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}" stroke="${c}" stroke-dasharray="${dash}"/>`});s+=`<text x="${W/2}" y="${H-15}" text-anchor="middle" fill="#657281" font-size="10">価格 →</text><text x="14" y="${H/2}" transform="rotate(-90 14 ${H/2})" text-anchor="middle" fill="#657281" font-size="10">内部参加 →</text>`;rows.filter(r=>isNum(r.price_score)&&isNum(r.internal_score)).forEach(r=>{const st=stateInfo(r.state),a=Math.abs(Number(r.flow_20d_pct_aum)||0),rad=Math.max(10,Math.min(23,9+Math.sqrt(a)*3.2)),cx=x(r.price_score),cy=y(r.internal_score);s+=`<g><title>${esc(etfLabel(r.ticker))}｜${esc(st.label)}｜Flow/AUM ${pct(r.flow_20d_pct_aum)}</title><circle cx="${cx}" cy="${cy}" r="${rad}" fill="${st.color}" fill-opacity=".15" stroke="${st.color}" stroke-width="1.5"/><text x="${cx}" y="${cy+3.5}" text-anchor="middle" fill="#eef2f6" font-size="9.5" font-weight="760">${esc(r.ticker)}</text></g>`});svg.innerHTML=s}
function parseFact(facts,prefix){return facts.find(x=>String(x).startsWith(prefix))||''}function factNum(text,re){const m=String(text).match(re);return m?m[1]:'—'}
function renderMacro(d){const facts=d.macro_why?.facts||[],cells=[['VIX',factNum(parseFact(facts,'VIX'),/VIX\s+([\d.]+)/)],['米10年',factNum(parseFact(facts,'米10年金利'),/米10年金利\s+([\d.]+)/)+'%'],['実質10年',factNum(parseFact(facts,'米10年実質金利'),/米10年実質金利\s+([\d.]+)/)+'%'],['広域ドル',factNum(parseFact(facts,'FRB Broad Dollar'),/Index\s+([\d.]+)/)]];$('macroStrip').innerHTML=cells.map(([l,v])=>`<div class="macro-cell"><div class="macro-label">${l}</div><div class="macro-value">${v}</div></div>`).join('');$('macroFacts').innerHTML=facts.map(x=>`<div class="obs">${esc(String(x).replace('Fear & Greed','市場心理指数').replace('/ neutral','/ 中立'))}</div>`).join('');$('hypotheses').innerHTML=(d.macro_why?.hypotheses||[]).map(x=>`<div class="obs">${esc(String(x).replace('Fear & Greed','市場心理指数').replace('Fear=','弱気側：').replace('Greed=','強気側：'))}</div>`).join('')||'<div class="sub">追加の読み筋なし</div>';$('missing').innerHTML=(d.macro_why?.missing||[]).map(x=>`<span>${esc(x)}</span>`).join('')||'<span>なし</span>'}
function renderStocks(groups){$('stocks').innerHTML=(groups||[]).length?groups.map(g=>`<div class="stock-group"><div class="stock-head"><div class="stock-etf">${esc(etfLabel(g.etf))}</div><div class="stock-count">正式条件通過 ${g.eligible_count??0}銘柄</div></div><div class="scroll"><table><thead><tr><th>銘柄</th><th>Theme</th><th>攻撃時順位</th><th>RS189</th><th>RS63</th><th>Theme強度</th></tr></thead><tbody>${(g.stocks||[]).map(s=>`<tr><td>${esc(s.symbol)}</td><td>${esc(s.peer_theme||'—')}</td><td>${s.attack_rank??'—'}</td><td>${isNum(s.rs189)?Number(s.rs189).toFixed(1):'—'}</td><td>${isNum(s.rs63)?Number(s.rs63).toFixed(1):'—'}</td><td>${isNum(s.peer_theme_score)?Number(s.peer_theme_score).toFixed(1):'—'}</td></tr>`).join('')}</tbody></table></div></div>`).join(''):'<div class="sub">正式条件通過候補なし</div>'}
function renderV38(d){const m=d.market_when||{},mode=String(m.mode||'').toUpperCase(),limit=m.new_entry_limit??'—';let text='市場モード未確認';if(mode==='STOP')text='新規エントリー 0。Rotationが強くても買わない。';if(mode==='DEFENSE')text='新規 0。既存は正式V38の防御ルールに従う。';if(mode==='SELECTIVE')text='最大4枠の補充。Stock RS189中心。';if(mode==='ATTACK')text='最大12枠。正式Eligibilityと攻撃時順位に従う。';$('v38Action').innerHTML=`<div class="summary-box"><div class="summary-title">現在の扱い</div><div class="summary-line"><b>${esc(modeLabel(mode))}</b>　${esc(text)}　<span class="micro">新規枠上限 ${limit}</span></div></div>`;if(['ATTACK','SELECTIVE'].includes(mode))$('v38Details').open=true}
function renderGuide(){const keys=['CURRENT_STRENGTH','INTERNAL_LEAD_WATCH','EARLY_ROTATION_WATCH','FLOW_INTERNAL_DIVERGENCE_WATCH','DISTRIBUTION_DETERIORATION_WARNING','INTERNAL_WEAK_FLOW_OUT','WEAK_BREAKDOWN'];$('guide').innerHTML=keys.map(k=>{const s=STATE[k];return `<div class="obs"><b class="${s.tone}">${esc(s.label)}</b>　${esc(s.meaning)}</div>`}).join('')}
function renderQuality(d,ctx){const missing=d.macro_why?.missing||[];$('quality').innerHTML=`<div class="quality"><div><strong>入力整合：</strong>${d.input_alignment?.status==='OK'?'RotationとV38の基準日一致':'不一致あり'}</div><div><strong>主導株照合：</strong>${ctx?.context_scope==='FULL_ETF_MEMBERSHIP_X_FULL_LEADERSHIP_EXPORT'?'現在ETF全構成銘柄 × Leadership全銘柄出力':'照合範囲に制限あり'}</div><div><strong>Industry履歴：</strong>現在構成の過去バックキャストはPIT未検証。業種状態は観測用。</div><div><strong>分配警戒：</strong>最近のPIT検証で警戒Contextとして残存。強制Exitではない。</div><div><strong>未取得：</strong>${missing.length?missing.join(' / '):'なし'}</div></div>`}
function render(d,ctx){$('asofBadge').textContent=`基準日 ${shortDate(d.asof)}`;const aligned=d.input_alignment?.status==='OK';$('alignBadge').textContent=aligned?'データ整合済み':'データ不一致';$('alignBadge').classList.toggle('ok',aligned);renderHero(d);const m=d.market_when||{},mode=String(m.mode||'').toUpperCase();$('mode').innerHTML=`<span class="status ${mode.toLowerCase()}">${esc(modeLabel(mode))}</span>`;$('modeSub').textContent=`新規枠上限 ${m.new_entry_limit??'—'}`;$('breadth').textContent=isNum(m.breadth50)?`${Number(m.breadth50).toFixed(1)}%`:'—';$('nqsar').textContent=`NQSAR ${m.nqsar||'—'}`;const facts=d.macro_why?.facts||[],fgText=parseFact(facts,'Fear & Greed'),fg=fgText.match(/Fear & Greed\s+([\d.]+)\s*\/\s*(.+)$/i);$('fg').textContent=fg?fg[1]:'—';$('fgSub').textContent=fg?rating(fg[2].trim()):'市場心理指数';const v=factNum(parseFact(facts,'VIX'),/VIX\s+([\d.]+)/),y=factNum(parseFact(facts,'米10年金利'),/米10年金利\s+([\d.]+)/);$('macroTop').textContent=`${v} / ${y}%`;const rows=allRows(d);const sectors=rows.filter(r=>r.level==='SECTOR'),industries=rows.filter(r=>r.level==='INDUSTRY');renderMarketList('sectorList',sectors);renderMarketList('industryList',industries);renderLeaders(d,ctx);renderChanges(d);renderMatrix('sectorMatrix',sectors);renderMatrix('industryMatrix',industries);renderMacro(d);renderV38(d);renderStocks(d.theme_stock?.formal_v38_context||[]);renderGuide();renderQuality(d,ctx)}
Promise.all([fetch(DATA_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`brief HTTP ${r.status}`);return r.json()}),fetch(CONTEXT_URL,{cache:'no-store'}).then(r=>r.ok?r.json():null).catch(()=>null)]).then(([d,ctx])=>render(d,ctx)).catch(err=>{$('error').innerHTML=`<div class="error">最新データを読み込めませんでした。<br>${esc(err.message)}</div>`});
