#!/usr/bin/env python3
"""Directional Options positioning wrapper with time-safe upstream price anchoring.

This module is intentionally one-way:
  * READS state.json / universe.csv / rotation leadership as upstream context.
  * NEVER writes back to Dashboard, V38, Rotation, or Leadership artifacts.
  * Writes only Options artifacts through build_options_positioning.main().

The options provider does not expose a trustworthy OI update timestamp or trade-side
classification. We therefore separate four clocks in every detailed record:
price session, price observation source, technical-history session, and option-chain
fetch time. "Put sold / Call bought" is never inferred from OI alone.
"""
import csv
import json
import math
import os
import sys
from pathlib import Path
from zoneinfo import ZoneInfo

import build_options_positioning as base

_orig_analyse_expiry = base.analyse_expiry
_orig_load_tickers = base.load_tickers

UPSTREAM_LEADERS = Path(os.environ.get(
    "V38_OPT_LEADERS_JSON", "rotation/data/rotation-theme56-stock-context.json"))
LEADER_TARGET_COUNT = int(os.environ.get("V38_OPT_LEADER_TARGET_COUNT", "10"))

_UPSTREAM_CACHE = None


def _finite(v):
    try:
        x = float(v)
    except (TypeError, ValueError):
        return None
    return x if math.isfinite(x) else None


def _clean_positioning_rows(df, kind):
    """Keep OI/IV-valid rows even when after-hours bid/ask/volume are zero."""
    if df is None or len(df) == 0:
        return base.pd.DataFrame()
    d = df.copy()
    for c in ("strike", "openInterest", "impliedVolatility", "volume", "bid", "ask"):
        if c not in d.columns:
            d[c] = base.np.nan
        d[c] = base.pd.to_numeric(d[c], errors="coerce")
    d = d[(d["strike"] > 0) & (d["openInterest"].fillna(0) > 0)]
    d = d[d["impliedVolatility"].between(base.MIN_IV, base.MAX_IV)]
    d["kind"] = kind
    return d[["strike", "openInterest", "impliedVolatility", "volume", "bid", "ask", "kind"]]


base._clean = _clean_positioning_rows


def _load_upstream_context():
    """Read the existing Dashboard snapshot as the price-session authority."""
    global _UPSTREAM_CACHE
    if _UPSTREAM_CACHE is not None:
        return _UPSTREAM_CACHE

    session_date = None
    try:
        raw = json.loads(Path(base.STATE_JSON).read_text(encoding="utf-8"))
        session_date = str(raw.get("date") or "")[:10] or None
    except Exception:
        pass

    prices = {}
    try:
        with Path(base.UNIVERSE_CSV).open(encoding="utf-8-sig", newline="") as fh:
            for row in csv.DictReader(fh):
                ticker = str(row.get("シンボル") or row.get("ticker") or "").strip().upper()
                if not ticker:
                    continue
                px = _finite(row.get("価格") or row.get("price"))
                prices[ticker] = {
                    "price": px,
                    "change_pct": _finite(row.get("価格変動 %, 1日") or row.get("change_pct")),
                    "volume": _finite(row.get("出来高, 1日") or row.get("volume")),
                }
    except Exception:
        pass

    _UPSTREAM_CACHE = {"session_date": session_date, "prices": prices}
    return _UPSTREAM_CACHE


def _history_session_date(px):
    try:
        ts = base.pd.Timestamp(px.index[-1])
        if ts.tzinfo is not None:
            ts = ts.tz_convert("America/New_York")
        return ts.date().isoformat()
    except Exception:
        return None


def _price_context(ticker, px, asof):
    """Choose a price whose market-session date is explicit.

    state.json + universe.csv are generated by the upstream Dashboard pipeline and are
    treated as the authoritative completed-session close. Yahoo history is used only
    when it actually contains that same session. This prevents an after-close options
    run from silently pairing today's chain with yesterday's close.
    """
    upstream = _load_upstream_context()
    expected = upstream.get("session_date")
    history_date = _history_session_date(px)
    yclose = _finite(px["Close"].iloc[-1]) if px is not None and not px.empty else None
    u = (upstream.get("prices") or {}).get(ticker, {})
    uclose = _finite(u.get("price"))

    if expected and uclose and uclose > 0:
        spot = uclose
        source = "upstream_universe_close"
        price_date = expected
        verified = True
    elif yclose and (not expected or history_date == expected):
        spot = yclose
        source = "yfinance_daily_close"
        price_date = history_date
        verified = bool(price_date)
    else:
        raise RuntimeError(
            f"price session mismatch expected={expected} yfinance={history_date} "
            f"universe_price={'yes' if uclose else 'no'}")

    observed = base.pd.Timestamp(asof)
    if observed.tzinfo is None:
        observed = observed.tz_localize("UTC")
    observed_et = observed.tz_convert(ZoneInfo("America/New_York")).isoformat()
    return {
        "spot": float(spot),
        "price_source": source,
        "price_session_date": price_date,
        "expected_session_date": expected or price_date,
        "history_session_date": history_date,
        "session_consistent": bool(verified and (not expected or price_date == expected)),
        "upstream_change_pct": _finite(u.get("change_pct")),
        "upstream_volume": _finite(u.get("volume")),
        "observed_at_utc": str(asof),
        "observed_at_et": observed_et,
    }


def _quote_mid(row):
    if row is None:
        return None
    bid = _finite(row.get("bid"))
    ask = _finite(row.get("ask"))
    if bid is None or ask is None or bid <= 0 or ask <= 0 or ask < bid:
        return None
    return (bid + ask) / 2.0


def _nearest_row(df, spot):
    if df is None or len(df) == 0:
        return None
    d = df.copy()
    if "strike" not in d.columns:
        return None
    d["strike"] = base.pd.to_numeric(d["strike"], errors="coerce")
    d = d[d["strike"].notna() & (d["strike"] > 0)]
    if d.empty:
        return None
    idx = (d["strike"] - float(spot)).abs().idxmin()
    return d.loc[idx].to_dict()


def _expected_move(calls, puts, spot, T):
    """Return both ATM-straddle and ATM-IV move; never hide the method used."""
    c = _nearest_row(calls, spot)
    p = _nearest_row(puts, spot)
    cmid, pmid = _quote_mid(c), _quote_mid(p)
    straddle = cmid + pmid if cmid is not None and pmid is not None else None
    straddle_pct = straddle / spot if straddle is not None and spot > 0 else None

    ivs = []
    for row in (c, p):
        if row:
            iv = _finite(row.get("impliedVolatility"))
            if iv is not None and base.MIN_IV <= iv <= base.MAX_IV:
                ivs.append(iv)
    atm_iv = sum(ivs) / len(ivs) if ivs else None
    iv_move = spot * atm_iv * math.sqrt(max(T, 1.0 / 365.0)) if atm_iv else None
    iv_pct = iv_move / spot if iv_move is not None and spot > 0 else None

    if straddle_pct is not None and 0.002 <= straddle_pct <= 0.60:
        move, method = straddle, "atm_straddle_mid"
    elif iv_move is not None:
        move, method = iv_move, "atm_iv_1sigma"
    else:
        move, method = None, "unavailable"

    atm_strike = None
    strikes = [_finite((c or {}).get("strike")), _finite((p or {}).get("strike"))]
    strikes = [x for x in strikes if x is not None]
    if strikes:
        atm_strike = sum(strikes) / len(strikes)

    return {
        "atm_strike": round(atm_strike, 4) if atm_strike is not None else None,
        "atm_iv": round(atm_iv, 6) if atm_iv is not None else None,
        "straddle_move": round(straddle, 4) if straddle is not None else None,
        "straddle_move_pct": round(straddle_pct, 6) if straddle_pct is not None else None,
        "iv_1sigma_move": round(iv_move, 4) if iv_move is not None else None,
        "iv_1sigma_move_pct": round(iv_pct, 6) if iv_pct is not None else None,
        "expected_move": round(move, 4) if move is not None else None,
        "expected_move_pct": round(move / spot, 6) if move is not None and spot > 0 else None,
        "expected_move_method": method,
        "expected_low": round(spot - move, 4) if move is not None else None,
        "expected_high": round(spot + move, 4) if move is not None else None,
    }


def _directional(rows, spot, side, n=3):
    vals = []
    field = "call" if side == "call" else "put"
    for row in rows or []:
        try:
            strike = float(row.get("k"))
            gex = float(row.get(field) or 0.0)
        except (TypeError, ValueError, AttributeError):
            continue
        if side == "call" and strike <= spot:
            continue
        if side == "put" and strike >= spot:
            continue
        if abs(gex) <= 0:
            continue
        vals.append((abs(gex), strike))
    vals.sort(reverse=True)
    return [dict(strike=float(strike), gex=float(gex)) for gex, strike in vals[:n]]


def _concentration(rows, spot, side):
    walls = _directional(rows, spot, side, n=10_000)
    total = sum(float(w["gex"]) for w in walls)
    share = float(walls[0]["gex"]) / total if walls and total > 0 else None
    lead = (float(walls[0]["gex"]) / float(walls[1]["gex"])
            if len(walls) >= 2 and float(walls[1]["gex"]) > 0 else None)
    return share, lead


def _repair_expiry(exp, spot):
    if not isinstance(exp, dict):
        return exp
    calls_above = _directional(exp.get("strikes"), spot, "call")
    puts_below = _directional(exp.get("strikes"), spot, "put")
    exp["call_walls"] = calls_above
    exp["put_walls"] = puts_below
    exp["call_wall"] = calls_above[0]["strike"] if calls_above else None
    exp["put_wall"] = puts_below[0]["strike"] if puts_below else None
    for prefix in ("call", "put"):
        share, lead = _concentration(exp.get("strikes"), spot, prefix)
        exp[f"{prefix}_wall_share"] = share
        exp[f"{prefix}_wall_vs_second"] = lead
    return exp


def _dist(level, spot, atr):
    if level is None:
        return {"px": None, "pct": None, "atr": None}
    a = _finite(atr) or 0.0
    return {
        "px": round(float(level), 2),
        "pct": round(float(level) / spot - 1.0, 5),
        "atr": round((float(level) - spot) / a, 2) if a > 0 else None,
    }


def _explain_wall(label, level, spot, atr):
    if level is None:
        return ("現値より上の有効なCall GEX集中は見つからない。" if label == "call"
                else "現値より下の有効なPut GEX集中は見つからない。")
    a = _finite(atr) or 0.0
    pct = (float(level) / spot - 1.0) * 100.0
    atr_units = abs(float(level) - spot) / a if a > 0 else None
    tail = f"現値から{pct:+.1f}%" + (f"、{atr_units:.1f} ATR。" if atr_units is not None else "。")
    if label == "call":
        return "現値より上のCall OI×推定Gamma最大集中。上値抵抗候補。" + tail
    return "現値より下のPut OI×推定Gamma最大集中。下値支持候補。" + tail


def analyse_expiry(calls, puts, spot, expiry, asof):
    result = _orig_analyse_expiry(calls, puts, spot, expiry, asof)
    if not result:
        return result
    result = _repair_expiry(result, float(spot))
    T = max(float(result.get("dte") or 1) / 365.0, 1.0 / 365.0)
    result.update(_expected_move(calls, puts, float(spot), T))
    return result


base.analyse_expiry = analyse_expiry


def _leader_score(x):
    def n(k, default=50.0):
        v = _finite(x.get(k))
        return default if v is None else v
    strength, rs189, rs63, rs21 = n("strength"), n("rs189"), n("rs63"), n("rs21")
    acc = _finite(x.get("slow_acceleration"))
    if acc is None:
        acc = _finite(x.get("acceleration")) or 0.0
    score = .36 * strength + .25 * rs189 + .20 * rs63 + .11 * rs21 + .08 * max(0, min(100, 50 + acc))
    if str(x.get("role") or "").upper() == "LEADER":
        score += 3
    if str(x.get("group_phase") or "").upper() in ("LEADING", "EMERGING"):
        score += 3
    if "BREAKOUT" in str(x.get("breakout_status") or "").upper():
        score += 3
    return max(0, min(100, score))


def _leader_targets():
    try:
        raw = json.loads(UPSTREAM_LEADERS.read_text(encoding="utf-8"))
    except Exception:
        return []
    best = {}
    def walk(node):
        if isinstance(node, list):
            for v in node:
                walk(v)
            return
        if not isinstance(node, dict):
            return
        symbol = node.get("symbol")
        if isinstance(symbol, str) and (node.get("role") or node.get("strength") is not None
                                        or node.get("rs189") is not None
                                        or node.get("stock_rank_within_group") is not None):
            ticker = symbol.strip().upper()
            score = _leader_score(node)
            if ticker and score > best.get(ticker, -1):
                best[ticker] = score
        for k, v in node.items():
            if k not in ("symbol", "name") and isinstance(v, (dict, list)):
                walk(v)
    walk(raw)
    return [t for t, _ in sorted(best.items(), key=lambda kv: (-kv[1], kv[0]))[:max(0, LEADER_TARGET_COUNT)]]


def load_tickers():
    """Existing Options targets + top upstream leaders; read-only enrichment."""
    base_targets = _orig_load_tickers()
    return list(dict.fromkeys(base_targets + _leader_targets()))


base.load_tickers = load_tickers


def _build_record_once(yf, tk, asof):
    """Build GEX with an explicitly verified completed-session spot."""
    y = yf.Ticker(tk)
    px = y.history(period="3mo", auto_adjust=False)
    if px is None or px.empty:
        raise RuntimeError("no price history")
    pc = _price_context(tk, px, asof)
    spot = pc["spot"]

    tr = base.pd.concat([
        px["High"] - px["Low"],
        (px["High"] - px["Close"].shift()).abs(),
        (px["Low"] - px["Close"].shift()).abs(),
    ], axis=1).max(axis=1)
    atr = _finite(tr.rolling(14).mean().iloc[-1])
    if atr is None or atr <= 0:
        atr = _finite(tr.tail(14).mean()) or max(spot * 0.02, 0.01)

    exps = base._select_expiries(list(y.options or []), asof, base.MAX_EXPIRY, include_nearest=True)
    if not exps:
        raise RuntimeError("no option expiries returned")
    per, expiry_errors = {}, []
    for expiry in exps:
        try:
            ch = y.option_chain(expiry)
            rec = analyse_expiry(ch.calls, ch.puts, spot, expiry, asof)
            if rec:
                per[expiry] = rec
        except Exception as exc:
            expiry_errors.append(f"{expiry}:{type(exc).__name__}")
    if not per:
        tail = " (" + ",".join(expiry_errors[:3]) + ")" if expiry_errors else ""
        raise RuntimeError("no usable expiry" + tail)

    agg_net = sum(v["net_gex"] for v in per.values())
    nearest_expiry = sorted(per)[0]
    swing_expiries = [e for e in per if 7 <= (base._expiry_dte(e, asof) or -999) <= 24]
    selected_expiry = (min(swing_expiries, key=lambda e: abs(base._expiry_dte(e, asof) - 14))
                       if swing_expiries else nearest_expiry)
    focus = per[selected_expiry]
    selection_basis = "swing" if selected_expiry in swing_expiries else "nearest"
    tech = base.tech_levels(px)
    cw, pw, gf = focus["call_wall"], focus["put_wall"], focus["gamma_flip"]

    rec = dict(
        ticker=tk,
        asof=asof,
        spot=round(spot, 2),
        atr14=round(atr, 4),
        tech={k: round(v, 2) for k, v in tech.items()},
        confluence=dict(
            call_wall=base.confluence(cw, tech, spot, atr),
            put_wall=base.confluence(pw, tech, spot, atr),
            gamma_flip=base.confluence(gf, tech, spot, atr)),
        range_pos=base.position_in_range(spot, pw, cw),
        explain=base.explain(spot, cw, pw, gf, focus["net_gex"], atr,
                             base.regime(spot, gf, atr)),
        source="yfinance_options+upstream_price",
        basis="positioning_proxy_not_observed_dealer_gamma",
        oi_basis="provider_open_interest_update_time_unavailable",
        nearest=nearest_expiry,
        selected_expiry=selected_expiry,
        selection_basis=selection_basis,
        call_wall=base.dist_block(cw, spot, atr),
        put_wall=base.dist_block(pw, spot, atr),
        gamma_flip=base.dist_block(gf, spot, atr),
        net_gex=round(focus["net_gex"], 2),
        net_gex_all=round(agg_net, 2),
        regime=base.regime(spot, gf, atr),
        confidence=focus["confidence"],
        expiries=per,
        stale=False,
        refresh_failed=False,
        refresh_attempted_at=asof,
        price_source=pc["price_source"],
        price_session_date=pc["price_session_date"],
        expected_session_date=pc["expected_session_date"],
        history_session_date=pc["history_session_date"],
        tech_session_date=pc["history_session_date"],
        session_consistent=pc["session_consistent"],
        options_observed_at=asof,
        oi_observed_at=None,
        upstream_change_pct=pc["upstream_change_pct"],
        upstream_volume=pc["upstream_volume"],
    )
    rec["expected_move"] = {
        k: focus.get(k) for k in (
            "atm_strike", "atm_iv", "straddle_move", "straddle_move_pct",
            "iv_1sigma_move", "iv_1sigma_move_pct", "expected_move",
            "expected_move_pct", "expected_move_method", "expected_low", "expected_high")
    }
    return rec


base._build_record_once = _build_record_once


def _repair_record(rec):
    if not isinstance(rec, dict):
        return rec
    spot = _finite(rec.get("spot"))
    if not spot:
        return rec
    per = rec.get("expiries") or {}
    if not isinstance(per, dict):
        return rec
    for exp in per.values():
        _repair_expiry(exp, spot)
    selected = rec.get("selected_expiry") or rec.get("nearest")
    focus = per.get(selected) if selected else None
    if not isinstance(focus, dict):
        return rec
    cw, pw, gf = focus.get("call_wall"), focus.get("put_wall"), focus.get("gamma_flip")
    rec["call_wall"] = _dist(cw, spot, rec.get("atr14"))
    rec["put_wall"] = _dist(pw, spot, rec.get("atr14"))
    rec["gamma_flip"] = _dist(gf, spot, rec.get("atr14"))
    rec["net_gex"] = focus.get("net_gex", rec.get("net_gex"))
    rec["regime"] = base.regime(spot, gf, rec.get("atr14"))
    rec["confidence"] = focus.get("confidence", rec.get("confidence", "LOW"))
    rec["oi_basis"] = "provider_open_interest_update_time_unavailable"
    rec["range_pos"] = base.position_in_range(spot, pw, cw)
    explain = base.explain(spot, cw, pw, gf, float(rec.get("net_gex") or 0.0),
                           rec.get("atr14"), rec.get("regime"))
    explain["call_wall"] = _explain_wall("call", cw, spot, rec.get("atr14"))
    explain["put_wall"] = _explain_wall("put", pw, spot, rec.get("atr14"))
    rec["explain"] = explain
    return rec


def _repair_history_dates(data):
    """A manual run after UTC midnight must not label the prior US session as today."""
    path = Path(base.HIST_CSV)
    if not path.is_file() or not isinstance(data, dict):
        return
    asof_day = str(data.get("asof") or "")[:10]
    session_by_ticker = {}
    for ticker, rec in (data.get("tickers") or {}).items():
        if isinstance(rec, dict) and not rec.get("refresh_failed"):
            day = rec.get("price_session_date")
            if day:
                session_by_ticker[str(ticker).upper()] = str(day)[:10]
    if not session_by_ticker:
        return
    with path.open(encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.DictReader(fh)); fields = list(rows[0].keys()) if rows else []
    changed = False
    for row in rows:
        ticker = str(row.get("ticker") or "").upper()
        if ticker in session_by_ticker and row.get("date") == asof_day:
            new_day = session_by_ticker[ticker]
            if new_day != row.get("date"):
                row["date"] = new_day; changed = True
    if changed and fields:
        with path.open("w", encoding="utf-8", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=fields); w.writeheader(); w.writerows(rows)


def _repair_output():
    path = Path(base.OUT_JSON)
    if not path.is_file():
        return
    data = json.loads(path.read_text(encoding="utf-8"))
    bad = []
    for ticker, rec in (data.get("tickers") or {}).items():
        _repair_record(rec)
        spot = _finite(rec.get("spot"))
        if not spot:
            continue
        cw = (rec.get("call_wall") or {}).get("px")
        pw = (rec.get("put_wall") or {}).get("px")
        if cw is not None and float(cw) <= spot:
            bad.append((ticker, "call", spot, cw))
        if pw is not None and float(pw) >= spot:
            bad.append((ticker, "put", spot, pw))
        if cw is not None and pw is not None and float(cw) == float(pw):
            bad.append((ticker, "same", spot, cw))
    if bad:
        raise RuntimeError(f"directional wall invariant failed: {bad[:10]}")
    upstream = _load_upstream_context()
    data["session_date"] = upstream.get("session_date")
    data["price_time_policy"] = "state_date_plus_universe_close_then_same_session_yfinance"
    data["oi_time_policy"] = "provider_open_interest_update_time_unavailable"
    data["upstream_read_only"] = ["state.json", "universe.csv", str(UPSTREAM_LEADERS)]
    path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    _repair_history_dates(data)
    sys.stderr.write(f"[opt-wall] time/directional invariants OK for {len(data.get('tickers') or {})} tickers\n")


if __name__ == "__main__":
    rc = base.main()
    _repair_output()
    sys.exit(rc)
